In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.1'

In [56]:
a=np.arange(10, 100, 10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
b = np.arange(0,3,.4)
b

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8])

In [58]:
np.zeros_like(b)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
arr2 = arr.reshape(2,-1)
arr2

array([[-1,  2, -1,  4, -1,  6],
       [-1,  8, -1, 10, -1, 12]])

In [100]:
arr2.ndim

2

In [101]:
arr2.shape

(2, 6)

In [102]:
arr2.size

12

In [103]:
arr2.dtype

dtype('int32')

In [104]:
arr2.itemsize

4

In [105]:
arr2.data

In [106]:
arr2.ravel()

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12])

In [112]:
arr2.T

array([[-1, -1],
       [ 2,  8],
       [-1, -1],
       [ 4, 10],
       [-1, -1],
       [ 6, 12]])

In [28]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [29]:
arr[arr % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [31]:
arr[arr % 2 == 1] = -1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12])

In [34]:
type(arr)

numpy.ndarray

In [41]:
out = np.where(arr % 2 == 1, -2, arr)
print(out)
print(arr)

[-2  2 -2  4 -2  6 -2  8 -2 10 -2 12]
[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12]


In [45]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.ones((3,4), dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [50]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.ones_like(arr)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [62]:
np.full_like(arr, 100)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [74]:
x = np.array([10,20,30,40,50,60])
y = np.array([1,2,3,4,5,6])
x-y

array([ 9, 18, 27, 36, 45, 54])

In [75]:
x*y

array([ 10,  40,  90, 160, 250, 360])

In [76]:
x ** y

array([        10,        400,      27000,    2560000,  312500000,
       -588640256], dtype=int32)

In [77]:
x.sum()

210

In [78]:
x.max()

60

In [79]:
x.min()

10

In [81]:
z = x.reshape(2,-1)
z

array([[10, 20, 30],
       [40, 50, 60]])

In [82]:
z.sum(axis=0)

array([50, 70, 90])

In [83]:
z.sum(axis=1)

array([ 60, 150])

In [84]:
z.min(axis=0)

array([10, 20, 30])

In [85]:
z.max(axis=1)

array([30, 60])

In [86]:
z.cumsum(axis=1)

array([[ 10,  30,  60],
       [ 40,  90, 150]], dtype=int32)

In [87]:
np.exp(y)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [88]:
np.sqrt(y)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [89]:
z.mean(axis=0)

array([25., 35., 45.])

In [93]:
np.median(z, axis=1)

array([20., 50.])

In [94]:
np.percentile(z, 60, axis=0)

array([28., 38., 48.])

In [95]:
x[2:4]

array([30, 40])

In [117]:
np.vstack((x,y))

array([[10, 20, 30, 40, 50, 60],
       [ 1,  2,  3,  4,  5,  6]])

In [118]:
np.hstack((x,y))

array([10, 20, 30, 40, 50, 60,  1,  2,  3,  4,  5,  6])

In [119]:
np.column_stack((x,y))

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4],
       [50,  5],
       [60,  6]])

In [121]:
np.concatenate((x,y))

array([10, 20, 30, 40, 50, 60,  1,  2,  3,  4,  5,  6])

In [123]:
np.array_split(x,4)

[array([10, 20]), array([30, 40]), array([50]), array([60])]

In [125]:
np.split(x, 3)

[array([10, 20]), array([30, 40]), array([50, 60])]

In [126]:
x @ x

9100

In [133]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [137]:
np.linspace(2,8,num=10)

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [138]:
np.sort(y)

array([1, 2, 3, 4, 5, 6])

In [139]:
np.partition(y,3)

array([2, 1, 3, 4, 5, 6])

In [1]:
%time

Wall time: 0 ns


In [2]:
%history

%time
%history
